# Generated by Django 4.2.6 on 2023-10-25 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255)),
                ('bairro', models.CharField(max_length=255)),
                ('municipio', models.CharField(max_length=255)),
                ('uf', models.CharField(max_length=2)),
                ('num_casa', models.BigIntegerField(default=0)),
                ('complemento', models.CharField(blank=True, max_length=255, null=True)),
                ('referencia', models.CharField(max_length=255)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
        ),
    ]
