# Generated by Django 4.2.6 on 2023-10-25 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quero_delivery', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.BigIntegerField()),
                ('produtos', models.JSONField()),
                ('endereco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quero_delivery.endereco')),
            ],
        ),
    ]
