# Generated by Django 4.2.6 on 2023-10-25 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quero_delivery', '0002_pedido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endereco',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
